# Generated by Django 5.2.7 on 2025-11-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_designrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий (для статуса «Принято в работу»)'),
        ),
        migrations.AddField(
            model_name='designrequest',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/', verbose_name='Готовый дизайн (для статуса «Выполнено»)'),
        ),
    ]
